services:
  my_postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "6004:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - elt_network

  elt_script:
    build:
      context: .  # Using the current directory
      dockerfile: Dockerfile
    environment:
      DB_HOST: my_postgres
      DB_NAME: mydatabase
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      - my_postgres
    networks:
      - elt_network

networks:
  elt_network:
    driver: bridge

volumes:
  pg_data:
